version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8443:8443" 
    environment:
      - "TLS_CERT_PATH=/app/certs/cert.pem"
      - "TLS_KEY_PATH=/app/certs/key.pem" 

  ngrok:
    image: ngrok/ngrok:latest
    command: http frontend:3000
    depends_on:
      - frontend
    environment:
      - NGROK_AUTHTOKEN=2ZmQ9ZIp7b7oDRTDMhBM3vScdzd_28UJ5pQ442aUCGJeCFnv7
