version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    container_name: frontend
    depends_on:
      - backend

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   command: http frontend:3000
  #   depends_on:
  #     - frontend
  #   environment:
  #     - NGROK_AUTHTOKEN=2ZmQ9ZIp7b7oDRTDMhBM3vScdzd_28UJ5pQ442aUCGJeCFnv7
